project:
  type: book
  output-dir: .

book:
  title: "Financial Anomalies"
  author: "Krishna Neupane"
  date: "8/24/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt




